# Generated by Django 5.0.3 on 2024-05-16 15:30

import letter.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.IntegerField(default=20153)),
                ('file', models.FileField(upload_to=letter.utils.file_directory_path)),
            ],
        ),
    ]
