# Generated by Django 5.0.3 on 2024-05-16 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helper', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serial',
            name='information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seraial', to='main.information'),
        ),
        migrations.AddField(
            model_name='fond',
            name='uzmtrk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.uzmtrk'),
        ),
    ]
