# Generated by Django 5.0.3 on 2024-03-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fond',
            name='uzmtrk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper.uzmtrk'),
        ),
    ]
