# Generated by Django 5.0.3 on 2024-03-29 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0003_fond_uzmtrk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serial',
            old_name='video',
            new_name='information',
        ),
    ]
